env:
  browser: true
  es2021: true
  'vue/setup-compiler-macros': true,
extends:
  - 'plugin:vue/vue3-recommended'
  - 'eslint:recommended'
  - '@vue/typescript/recommended'
parser: 'vue-eslint-parser'
parserOptions:
  parser: '@typescript-eslint/parser'
  ecmaVersion: 12
plugins:
  - vue
  - '@typescript-eslint'
rules: {}
